language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libboost-all-dev
  - sudo apt-get install -y libssl-dev
  - sudo apt-get install -y libsqlite3-dev
  - sudo apt-get install -y libdb++-dev
script: ./configure && make && sudo make install
